add html our program
akushnirenko10/project-19 pull request #22
Opened 2022-05-13 21:11 UTC by elenashy

2022-05-14 11:33 UTC, akushnirenko10 requested changes

2022-05-14 15:59 UTC, elenashy commented on src/sass/layout/_problems.scss
> +    color: #FF6B09;
оке) еще не успела )

2022-05-14 17:47 UTC, akushnirenko10 requested changes

2022-05-14 17:47 UTC, akushnirenko10 commented on src/partials/program.html
>          <h2 class="program__title">Our program</h2>
это section__title

2022-05-14 17:47 UTC, akushnirenko10 commented on src/sass/layout/_program.scss
> +.program {
.program {
    background-color: var(--third-color);
      &__title {
          font-weight: 800;
          text-align: center;
      }
      &__list{
          position: relative;
      
      }
}
используй sass

2022-05-15 10:46 UTC, akushnirenko10 approved these changes

2022-05-15 10:47 UTC, merged