Features contacts
akushnirenko10/project-19 pull request #30
Opened 2022-05-14 10:55 UTC by valkiria91

Создает разметку и оформление мобильной версии контактной -формы

2022-05-14 11:26 UTC, DmytryVityuk commented
Тестовый комментарий

2022-05-14 11:30 UTC, akushnirenko10 requested changes

2022-05-14 11:30 UTC, akushnirenko10 commented on src/partials/contacts.html
> +<section class="section section__request">
почему не просто request?

2022-05-14 11:30 UTC, akushnirenko10 commented on src/sass/layout/_contacts.scss
> +    max-width: 1680px;
У нас это в контейнере прописано. Если нужно ограничить, то контейнером секцию оберни

2022-05-14 11:30 UTC, akushnirenko10 commented on src/sass/layout/_contacts.scss
> +    font-family: 'Montserrat';
лучше использовать inherit

2022-05-14 11:34 UTC, valkiria91 commented on src/sass/layout/_contacts.scss
> +    max-width: 1680px;
Мнен надо чисто картинку ограничить, что б она больше 1680 не тянулась , если я ее в контейнер запихну, то она будет по размеру контейнера

2022-05-15 17:40 UTC, akushnirenko10 requested changes

2022-05-15 17:40 UTC, akushnirenko10 commented on src/sass/layout/_contacts.scss
> +    transition: 250ms cubic-bezier(0.4, 0, 0.2, 1);
transition: background-color var(--animation);

2022-05-15 17:44 UTC, akushnirenko10 approved these changes

2022-05-15 17:45 UTC, merged